trigger:
  branches:
    include:
      - main

pool:
  name: 'Default'

variables:
  dockerRegistryServiceConnection: 'DockerHubConnection'
  imageRepository: 'sofiya56/library-app'
  dockerfilePath: 'Dockerfile'

steps:
  - script: |
      python -m pip install --upgrade pip
      python -m pip install -r requirements.txt
    displayName: 'Build project (install dependencies)'

  - script: |
      python -m pip install pytest
      python -m pytest tests --junitxml=test-results.xml
    displayName: 'Run unit tests'

  - task: PublishTestResults@2
    displayName: 'Publish test results'
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: 'test-results.xml'
      testRunTitle: 'Unit tests'

  - task: Docker@2
    displayName: 'Build Docker image'
    inputs:
      command: build
      containerRegistry: $(dockerRegistryServiceConnection)
      repository: $(imageRepository)
      dockerfile: $(dockerfilePath)
      tags: |
        latest
        $(Build.BuildId)

  - task: Docker@2
    displayName: 'Push Docker image'
    inputs:
      command: push
      containerRegistry: $(dockerRegistryServiceConnection)
      repository: $(imageRepository)
      tags: |
        latest
        $(Build.BuildId)